import { createClientFromRequest } from 'npm:@base44/sdk@0.8.46';

const TYPES = ['prayer', 'sermon', 'scripture_study'];
const DISCLOSURE = 'Generated by EVANGEL. Verify interpretation with trusted teachers and source material.';
const MAX_NOTES = 12000;
const MAX_PROMPT = 4000;

function response(status, body) {
  return Response.json(body, { status });
}

function validResearchBundle(bundle) {
  return Boolean(bundle?.passage?.ref && bundle?.passage?.text && bundle?.source?.key);
}

function allowedCitation(citation, bundle) {
  const value = typeof citation === 'string' ? citation : citation?.reference;
  if (!value) return false;
  if (value === bundle.passage.ref) return true;
  return (bundle.words || []).some((word) =>
    (word.occurrences || []).includes(value) || word.evidenceSource === value
  );
}

function sourceLanguageInsight(insight, bundle) {
  const word = (bundle.words || []).find((entry) =>
    entry.lemma === insight?.lemma && entry.evidenceSource === insight?.evidence_source
  );
  if (!word) return null;
  return {
    language: word.language || insight.language || '',
    lemma: word.lemma,
    transliteration: word.transliteration || '',
    pronunciation: word.pronunciation || '',
    meaning: word.contextualSenses?.[0] || word.standardGloss || '',
    evidence_source: word.evidenceSource,
  };
}

export default async function(req) {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (!user) return response(401, { error: 'Unauthorized' });

    const body = await req.json().catch(() => null);
    if (!body || !TYPES.includes(body.type)) {
      return response(400, { error: 'invalid_generator_type', allowed: TYPES });
    }
    if (!validResearchBundle(body.researchBundle)) {
      return response(400, { error: 'verified_passage_required' });
    }

    const creationPrompt = String(body.creationPrompt || '').trim().slice(0, MAX_PROMPT);
    if (!creationPrompt) return response(400, { error: 'creation_prompt_required' });
    const supportingNotes = String(body.supportingNotes || body.sourceNotes || '').trim().slice(0, MAX_NOTES);
    const evidence = JSON.stringify(body.researchBundle);
    const interview = JSON.stringify(body.interview || {});
    const prompt = [
      'You are EVANGEL, a careful, vivid, and human Scripture writing assistant.',
      `Create a complete ${body.type}. The subscriber's CREATOR IDEA is the primary instruction. Follow its subject, purpose, people, story, tone, requested elements, and desired ending.`,
      'Use the verified Scripture to ground and deepen the subscriber’s idea, never to replace the idea with a generic message.',
      'Avoid generic filler, repeated platitudes, vague introductions, and interchangeable points. Make every section serve the specific creator idea.',
      'For sermons, begin with a recognizable human struggle, develop a compelling opening, faithful context, an emotional movement from tension toward grounded hope, concrete application, and a closing prayer or invitation appropriate to the request and selected structure.',
      body.type === 'sermon'
        ? 'Use exactly one relevant original-language insight from VERIFIED EVIDENCE when words are supplied. Give the Greek or Hebrew spelling, transliteration, a plain contextual meaning, and weave its significance naturally into the sermon. Never turn the sermon into a vocabulary dump. If no verified word is supplied, do not invent one and state the limitation in warnings.'
        : 'Use original-language evidence only when it genuinely serves the requested work.',
      'For prayers, directly address the stated need with warmth, specificity, and language suitable for reading aloud.',
      'Use only the supplied evidence for Bible quotations, references, Hebrew, Aramaic, and Greek claims.',
      'Clearly separate verified Scripture, linguistic evidence, interpretation, tradition-specific perspective, application, illustration, and prayer.',
      'Never claim to speak for God or present generated language as Scripture.',
      'Concordant word study must preserve contextual range and must not claim that one English gloss fits every occurrence.',
      `CREATOR IDEA: ${creationPrompt}`,
      `SUPPORTING NOTES: ${supportingNotes}`,
      `INTERVIEW: ${interview}`,
      `VERIFIED EVIDENCE: ${evidence}`,
    ].join('\n\n');

    const generated = await base44.integrations.Core.InvokeLLM({
      prompt,
      response_json_schema: {
        type: 'object',
        properties: {
          title: { type: 'string' },
          central_truth: { type: 'string' },
          sections: {
            type: 'array',
            items: {
              type: 'object',
              properties: {
                kind: { type: 'string' },
                heading: { type: 'string' },
                content: { type: 'string' },
              },
              required: ['kind', 'heading', 'content'],
            },
          },
          citations: { type: 'array', items: { type: 'string' } },
          language_insights: {
            type: 'array',
            items: {
              type: 'object',
              properties: {
                language: { type: 'string' }, lemma: { type: 'string' }, transliteration: { type: 'string' },
                pronunciation: { type: 'string' }, meaning: { type: 'string' }, evidence_source: { type: 'string' },
              },
              required: ['language', 'lemma', 'transliteration', 'meaning', 'evidence_source'],
            },
          },
          warnings: { type: 'array', items: { type: 'string' } },
        },
        required: ['title', 'sections', 'citations', 'language_insights', 'warnings'],
      },
    });

    const citations = (generated?.citations || []).filter((citation) =>
      allowedCitation(citation, body.researchBundle)
    );
    const rejectedCount = (generated?.citations || []).length - citations.length;
    const languageInsights = (generated?.language_insights || []).map((insight) =>
      sourceLanguageInsight(insight, body.researchBundle)
    ).filter(Boolean).slice(0, body.type === 'sermon' ? 1 : 3);
    const fallbackWord = body.type === 'sermon' ? body.researchBundle.words?.[0] : null;
    if (!languageInsights.length && fallbackWord) {
      languageInsights.push(sourceLanguageInsight({ lemma: fallbackWord.lemma, evidence_source: fallbackWord.evidenceSource }, body.researchBundle));
    }
    const warnings = [...(generated?.warnings || [])];
    if (body.type === 'sermon' && !languageInsights.length) warnings.push('No verified Greek or Hebrew word was available for this passage, so no original-language claim was added.');
    if (rejectedCount) warnings.push(`${rejectedCount} unsupported citation(s) were removed.`);

    return response(200, {
      type: body.type,
      title: generated?.title || 'EVANGEL Draft',
      central_truth: generated?.central_truth || '',
      sections: Array.isArray(generated?.sections) ? generated.sections : [],
      citations,
      language_insights: languageInsights,
      warnings,
      disclosure: DISCLOSURE,
    });
  } catch (error) {
    return response(500, { error: 'generation_failed', message: error?.message || 'Unknown error' });
  }
}