export function resultToText(result) {
  if (!result) return '';
  if (typeof result.text === 'string') return result.text;
  const sections = Array.isArray(result.sections) ? result.sections : [];
  return sections.map((section) => [section.heading, section.content].filter(Boolean).join('\n')).filter(Boolean).join('\n\n');
}

export default function GeneratedResult({ result, onUseDraft }) {
  if (!result) return null;
  const text = resultToText(result);
  return <section className="generated-result glass" aria-live="polite">
    <p className="eyebrow">GENERATED DRAFT</p>
    <h3>{result.title || 'Your EVANGEL draft'}</h3>
    <pre>{text}</pre>
    {result.warnings?.map((warning) => <p className="source-warning" key={warning}>{warning}</p>)}
    <small>{result.disclosure || 'Generated by EVANGEL. Verify interpretation before public use.'}</small>
    <div className="editor-actions"><button className="primary" onClick={() => onUseDraft(result.title || '', text)}>Use as editable draft</button></div>
  </section>;
}