export function resultToText(result) {
  if (!result) return '';
  if (typeof result.text === 'string') return result.text;
  const sections = Array.isArray(result.sections) ? result.sections : [];
  const body = sections.map((section) => [section.heading, section.content].filter(Boolean).join('\n')).filter(Boolean).join('\n\n');
  const insights = Array.isArray(result.language_insights) ? result.language_insights : [];
  const wordStudy = insights.map((word) => [
    'Original-language insight',
    `${word.language}: ${word.lemma}${word.transliteration ? ` (${word.transliteration})` : ''}`,
    word.pronunciation ? `Pronounced: ${word.pronunciation}` : '',
    word.meaning,
    word.evidence_source ? `Source: ${word.evidence_source}` : '',
  ].filter(Boolean).join('\n')).join('\n\n');
  return [body, wordStudy].filter(Boolean).join('\n\n');
}

export default function GeneratedResult({ result, onUseDraft }) {
  if (!result) return null;
  const text = resultToText(result);
  return <section className="generated-result glass" aria-live="polite">
    <p className="eyebrow">GENERATED DRAFT</p>
    <h3>{result.title || 'Your EVANGEL draft'}</h3>
    <pre>{text}</pre>
    {result.language_insights?.map((word) => <div className="language-insight" key={`${word.lemma}-${word.evidence_source}`}><b>Original-language insight · {word.language}: {word.lemma}</b><span>{word.transliteration}{word.pronunciation ? ` · ${word.pronunciation}` : ''}</span><p>{word.meaning}</p><small>{word.evidence_source}</small></div>)}
    {result.warnings?.map((warning) => <p className="source-warning" key={warning}>{warning}</p>)}
    <small>{result.disclosure || 'Generated by EVANGEL. Verify interpretation before public use.'}</small>
    <div className="editor-actions"><button className="primary" onClick={() => onUseDraft(result.title || '', text)}>Use as editable draft</button></div>
  </section>;
}