import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';

test('generator requires evidence and labels generated content', () => {
  const source = fs.readFileSync('base44/functions/generateFaithContent/entry.ts', 'utf8');
  assert.match(source, /verified_passage_required/);
  assert.match(source, /Generated by EVANGEL/);
  assert.match(source, /InvokeLLM/);
  assert.match(source, /prayer.*sermon.*scripture_study/s);
});

test('frontend generator client uses the shared Base44 client', () => {
  const source = fs.readFileSync('src/features/generators/generatorClient.js', 'utf8');
  assert.match(source, /base44\.functions\.invoke\('generateFaithContent'/);
  assert.doesNotMatch(source, /createClient/);
});