export const EVANGEL_WHITE_PAPER={
 title:'EVANGEL: Scripture Understood, Explored, and Lived',
 summary:'EVANGEL is a voice-first Scripture companion that connects careful study, prayer, sermon creation, notes, and saved spiritual work without presenting artificial intelligence as spiritual authority.',
 sections:[
 {id:'summary',title:'1. Executive Summary',body:['EVANGEL helps people open Scripture, ask meaningful questions, listen, study, pray, create, and remember. The experience is designed for individuals, families, pastors, teachers, churches, and ministry communities.','Its central promise is clarity. Quoted Scripture, source evidence, translation, interpretation, and personal reflection remain distinguishable so confidence never outruns evidence.']},
 {id:'need',title:'2. The Need for an Accessible Scripture Companion',body:['Bible reading, notes, prayers, sermons, and digital conversations are often scattered across unrelated tools. EVANGEL keeps the journey connected while making the first step simple for people who may feel intimidated by formal study.']},
 {id:'mission',title:'3. The EVANGEL Mission',body:['We created EVANGEL as believers and educators using technology in service to God. The mission is to make careful Scripture engagement welcoming, memorable, and useful in everyday life.']},
 {id:'concordant',title:'4. The Concordant Study Method',body:['The Concordant method begins by observing a word or expression where it appears, comparing its usage across passages, and allowing context and grammar to guide meaning. It does not treat one English gloss as a complete definition.','EVANGEL uses this method as a study discipline. It is not endorsed by concordant.org, and no outside ministry endorsement is implied. Users are encouraged to examine the actual passage and consult multiple responsible sources.']},
 {id:'evidence',title:'5. Scripture Sources and Evidence Layers',body:['EVANGEL distinguishes quoted Scripture, ancient-language source text, source evidence, translation choices, interpretation, and personal reflection. These layers help users see what a passage says and where human judgment begins.']},
 {id:'languages',title:'6. Hebrew and Greek Word Education',body:['Original-language insight includes the written word, transliteration, pronunciation guidance, grammar when available, contextual possibilities, and a named source. Hebrew and Greek words are educational aids, not decorative proof. Their meaning depends on sentence, genre, history, and usage.']},
 {id:'creation',title:'7. Prayer, Sermon, and Scripture Creation',body:['Subscribers can begin with their own idea or notes, answer simple questions about length and style, and create a prayer, study, or sermon. Sermons are designed to include verified original-language insight and move from honest human struggle toward Scripture-grounded hope.','Generated work is editable and should be reviewed before teaching or sharing.']},
 {id:'voice',title:'8. Voice, Listening, and Accessibility',body:['EVANGEL supports listening and voice-first interaction with six curated voices: Marin, Coral, Shimmer, Cedar, Onyx, and Echo. Device speech remains a resilient fallback. Realtime and narration capabilities are clearly distinguished.']},
 {id:'folders',title:'9. Creator Notes, Folders, and Saved Work',body:['Notes can become prayers, studies, or sermons. Users can save creations into named folders, return to earlier work, delete material, or start over. The goal is an understandable library rather than another disappearing conversation.']},
 {id:'space',title:'10. The Navigable 3D Faith Space',body:['Faith Space presents saved verses, prayers, notes, studies, and sermons as a navigable memory map. Cards remain readable, movable, searchable, and mirrored in a simple list for people who prefer direct navigation.']},
 {id:'ai',title:'11. Responsible Artificial Intelligence',body:['AI assists with organization, explanation, and drafting. It does not claim revelation, divine appointment, or the authority to speak for God. Strong language is not a substitute for evidence.']},
 {id:'privacy',title:'12. Privacy, Subscriber Protection, and Security',body:['Premium voice access is authenticated, entitlement-checked, allowlisted, and rate-limited. Provider keys stay on the server. Saved records use ownership rules, and billing is handled through Stripe-hosted surfaces rather than exposing card data to EVANGEL.']},
 {id:'uses',title:'13. Uses for Individuals, Families, Churches, and Educators',body:['Individuals can build daily practices. Families can explore age-appropriate Scripture together. Churches and educators can prepare material, organize notes, and teach source awareness while retaining human pastoral responsibility.']},
 {id:'architecture',title:'14. Product Architecture in Plain Language',body:['The interface runs as a responsive web application. Base44 provides authenticated data and backend functions. Sensitive provider calls occur on the server. A shared FaithItem model connects saved work across Creator, Library, and Faith Space.']},
 {id:'limits',title:'15. Limitations and Human Discernment',body:['Translations involve judgment, manuscript questions can be complex, and generated explanations can be incomplete. Users should read surrounding context, consult qualified teachers and sources, and never use EVANGEL as the sole basis for high-stakes spiritual, medical, legal, or safety decisions.']},
 {id:'future',title:'16. Future Vision',body:['The future of EVANGEL is deeper source transparency, stronger accessibility, thoughtful community tools, and a calmer spatial library. Growth will remain guided by usefulness, privacy, evidence, and humility.']},
 {id:'conclusion',title:'17. Conclusion',body:['EVANGEL invites people to open the Word, follow the evidence, ask thoughtful questions, and carry what they learn into life. Technology can illuminate the road, but faith, wisdom, community, and discernment remain human and sacred responsibilities.']}
 ]
};